from datetime import datetime, timezone, timedelta
from milestone2_engine.schemas import SecurityEvent

def sample_events():
    base = datetime.now(timezone.utc)
    specs = [
        dict(event_id="EVT001", event_type="Authentication", failed_login_attempts=1, login_frequency=3, login_hour=10, connection_frequency=4, unique_destination_count=2, protocol="HTTPS", events_per_user=5, unique_ip_count=1, after_hours_activity=0, cvss_score=1.2, vulnerability_count=0, severity_score=1.0, malware_detected=0, event_frequency=4, source_country="India", destination_country="India", impossible_travel_flag=0, user="Rahul", asset="HR-Portal"),
        dict(event_id="EVT002", event_type="Brute Force", failed_login_attempts=18, login_frequency=36, login_hour=2, connection_frequency=18, unique_destination_count=4, protocol="TCP", events_per_user=26, unique_ip_count=5, after_hours_activity=1, cvss_score=8.9, vulnerability_count=2, severity_score=8.5, malware_detected=0, event_frequency=31, source_country="India", destination_country="USA", impossible_travel_flag=1, user="Rahul", asset="Auth-Server-01"),
        dict(event_id="EVT003", event_type="Malware", failed_login_attempts=2, login_frequency=4, login_hour=14, connection_frequency=28, unique_destination_count=18, protocol="TCP", events_per_user=41, unique_ip_count=8, after_hours_activity=0, cvss_score=9.4, vulnerability_count=4, severity_score=9.6, malware_detected=1, event_frequency=48, source_country="India", destination_country="Russia", impossible_travel_flag=1, user="Aisha", asset="Finance-DB"),
        dict(event_id="EVT004", event_type="Phishing", failed_login_attempts=3, login_frequency=8, login_hour=21, connection_frequency=8, unique_destination_count=5, protocol="HTTPS", events_per_user=11, unique_ip_count=3, after_hours_activity=1, cvss_score=4.5, vulnerability_count=1, severity_score=4.2, malware_detected=0, event_frequency=14, source_country="India", destination_country="Singapore", impossible_travel_flag=0, user="Neha", asset="Mail-Gateway"),
        dict(event_id="EVT005", event_type="SQL Injection", failed_login_attempts=4, login_frequency=9, login_hour=12, connection_frequency=15, unique_destination_count=7, protocol="TCP", events_per_user=16, unique_ip_count=4, after_hours_activity=0, cvss_score=7.8, vulnerability_count=2, severity_score=7.0, malware_detected=0, event_frequency=22, source_country="India", destination_country="India", impossible_travel_flag=0, user="Vikram", asset="Web-API"),
        dict(event_id="EVT006", event_type="Privilege Escalation", failed_login_attempts=11, login_frequency=15, login_hour=3, connection_frequency=20, unique_destination_count=9, protocol="SSH", events_per_user=32, unique_ip_count=6, after_hours_activity=1, cvss_score=9.1, vulnerability_count=3, severity_score=9.0, malware_detected=0, event_frequency=29, source_country="India", destination_country="USA", impossible_travel_flag=1, user="Arjun", asset="Linux-Server"),
        dict(event_id="EVT007", event_type="Network", failed_login_attempts=0, login_frequency=2, login_hour=11, connection_frequency=5, unique_destination_count=2, protocol="UDP", events_per_user=4, unique_ip_count=1, after_hours_activity=0, cvss_score=0.5, vulnerability_count=0, severity_score=0.7, malware_detected=0, event_frequency=5, source_country="India", destination_country="India", impossible_travel_flag=0, user="Meera", asset="DNS-01"),
        dict(event_id="EVT008", event_type="Authentication", failed_login_attempts=14, login_frequency=30, login_hour=1, connection_frequency=12, unique_destination_count=3, protocol="SSH", events_per_user=23, unique_ip_count=4, after_hours_activity=1, cvss_score=6.2, vulnerability_count=1, severity_score=6.8, malware_detected=0, event_frequency=27, source_country="India", destination_country="UK", impossible_travel_flag=0, user="Sahil", asset="VPN-Gateway"),
    ]
    return [SecurityEvent(timestamp=base-timedelta(hours=i*3), **s) for i,s in enumerate(specs)]
